#!/bin/sh
set -e
if [ "$1" = "remove" ]; then
  systemctl --global disable studio-schreibtisch.service >/dev/null 2>&1 || true
fi
if [ "$1" = "remove" ] && [ -d /run/systemd/system ]; then
  systemctl disable --now studio-setup.service || true
fi
exit 0
